services:
  backend:
    build: ./backend
    volumes:
      - snacks-data:/app/data
    ports:
      - "8000:8000"
    networks:
      - sceats-network
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./client
    ports:
      - "5173:5173"
    networks:
      - sceats-network
    depends_on:
      - backend

volumes:
  snacks-data:

networks:
  sceats-network:
    driver: bridge
